name: "Hello World Action"
description: "Minimal bash action that prints a message"
inputs:
  message:
    description: "Message to print"
    required: false
    default: "Hello, world from custom action!"
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - run: entrypoint.sh
      shell: bash
